
&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
	
КонецПроцедуры

&НаКлиенте
Процедура ПриОткрытии(Отказ)
	РеквизитТекст = "<html><head>
                     |<meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"">
                     |<link rel=""stylesheet"" type=""text/css"" href=""v8help://service_book/service_style"">
                     |<base href=""v8config://92b4395d-6d77-4d87-9c72-1ce2fcbbdffa/mdobject/idba69ea48-7a85-4e5a-86d8-633d0703cfdd/038b5c85-fb1c-4082-9c4c-e69f8928bf3a"">
                     |</head>
                     |<body>
                     |<div><span id=""docs-internal-guid-5667f772-7fff-3324-75b6-ed117e720c9c"">
                     |<p dir=""ltr"" style=""line-height:1.38;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 12pt; font-family: Arial; background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ЧТО ОЗНАЧАЮТ ИКОНКИ В СТАТУСАХ ЗАКАЗОВ НА ПРИОБРЕТЕНИЕ&nbsp;</span></p><br>
                     |<p dir=""ltr"" style=""line-height:1.38;margin-right: 6.850393700787464pt;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Заказы на приобретение по мере выполнения над ними действий и операций меняют свои статусы. 
                     |Для отображения статуса заказа используются как словесное описание, так и цветные иконки.&nbsp;</span></p><br>
                     |<p dir=""ltr"" style=""line-height:1.38;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">“Заказ на приобретение” – сокращенно ЗП.</span></p>
                     |<p dir=""ltr"" style=""line-height:1.38;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">“Финансовое планирование” – сокращенно ФП.&nbsp;</span></p><br>
                     |<div dir=""ltr"" style=""margin-left:0pt;"" align=""left"">
                     |<table style=""border:none;border-collapse:collapse;""><colgroup><col width=""33""><col width=""628""></colgroup>
                     |<tbody>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #434343 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAG2SURBVHgBjVNbasJQEJ28tElBS92AO2go/hVsXYH++ukK2q7AuIO6Aj/91QVIRfFLEXdQN2DRUJIm5tE54UaMSHVgyM3cmTOvcyU6kX6//yJJUp2PDdYybPy/iuMY2mk2m+tjfyk99Hq9O8Mw2nx8y6kqaayyLCd3YRQl6vk+fj8cx+m0Wq3tAUAEf6qKYt7kcshI96USFQoFUjWNvjebRLmCBGQfhisGqQFEBQAyawjO55Ogx0qFdMPItOY6Di0XC7Jtm2LPM0W17xL3XFZk+etW16lYLNJTtUr/yWwyod1uRz+uS1EU1WQut50XZSPzJYEPfDEnbqmBKZkYFno+LfucwAe+Gs+G4+oJgCIArhXMiUvHsSynxmC/vxoAm0kFAOuYd4zpXitYKXjBsgLA0A+CxOjyZC8JfDIAPMkBAEAS7PmSLOfzA6FAbZm5PeZD95cNNu93Np2erQQ2cACtejyvMAy7eBequLRI1595v2a83dJ4NEq2AsVwEZRSGYkCprLneRZiM49J13WL1/MKYoEbinhMzDjwn3yRGcGZx3QsoDZ/LK7mgb+mMK8ZZMi2AVo+9v8DuXL1PbrtJVMAAAAASUVORK5CYII=""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #434343 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ЧЕРНОВИК</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Сотрудник начал создавать ЗП, но еще не решил, что ЗП можно пускать дальше по потоку.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFUSURBVHgBnVPLcYMwEBXiZ8glJdBBKCFUYF850kE6MO4gVMCRq11BUgIdhBJySMACBHkrwOMhMWOyMzuSVrtvP3rS2EyyLHvWNG2L7Q7qkQ3nvO970kMYhsW1vzZt0jR9dF13j+2LZRjMhHLO1Z3sOqWirun4WpblIYqizwvAGPxm6Lq/sSzKyP4SVKBAGilzgAQEolJQZhPBjm3fDB5bYRv4UKKxWqahZ0/n/OPBcRaD55V8VRXrui7gCNrbC2XfqoTmBKAdteBPw1ojpmnSkLcKQP8HAB8q9tZHzoGgRY83XityiMkJ4FS3LVsrFwBM8kgA9DT3ykQoojYHt9+xSc4DTe8S0TRMSpnQv1BDrKoqbto2Pw+oi5krIRj5CiFisikA4jRAgrppkm8wDA5Tj0o6+kjISuxD6cn0D+juF/2I2lhisO0Jqz+aC4CcYDtSy9f+P5avvgZo/G7wAAAAAElFTkSuQmCC""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ПОДГОТОВЛЕН</span><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> </span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">(не попадает на ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Сотрудник обозначил свой ЗП как готовый для запуска по потоку и он передается руководителю на утверждение. Без установки модуля “Организующая схема” все пользователи, у кого есть право одобрять заказы подчиненных, будут видеть заказы всех сотрудников, у кого такого права нет. После установки “Оргсхемы” связь между руководителем и его подчиненными становится как в реальной жизни.&nbsp;</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAF8SURBVHgBjVNBTgJBEKyeFb0pRD144wfiC4QXgE8gwYMn8QXAD/DkQRKegL4A/cHyArh50AhXIctYPbuzrhsFOtlsZ6a7umaqRpCL90dUjUFdLBoWKOuaAKEVhMslemc3mGXrxSfTIYrFNTprizY2haDPAb1SE4sUQJsPI4yZVnwdp7/wN7EWCxFcsrCamRpKgJqC7OmCm5w0a2OwQrOUozp/QNkWMOJ+xX3s4fKdvHFjv4BpUhcet3Cx6QSfA4xtwobHrRk2d/ymWeEKW0LILs0FDYMM9Tztv0JrJL4fBaj/AFi8YsfgfU0QTy2bDJ3irgCqjM8VYJYk57sCBJQ1SUPDsz/HbFBVRbY1a41XgYYggMWT3zwoYLgNgKqNfG5obefEjwH6TG5jUIRflDPveZ2sA/x0/u9PWmg7gDmtbCNnkNTKKlVEZej7Iz6sis1Y2Z09sXL6mBQkitD1TP4LnRwE6P56TNlQz0d7BBKnimc008vW+zq9jk3k4xt6J4fAI2xSCgAAAABJRU5ErkJggg==""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">УТВЕРЖДЕН РУКОВОДИТЕЛЕМ</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Руководитель ознакомился с ЗП, подтвердил, что расход заслуживает рассмотрения на финансовом планировании.&nbsp;</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">С этого момента ЗП попадает в поле зрения сотрудника финансовой службы, который проверяет ЗП с точки зрения правильности привязки расхода к нужному фонду, указаны ли в ЗП все данные, необходимые для принятия решения по заказу на самом ФП.&nbsp;</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Если сотруднику дано право допускать заказы к рассмотрению на ФП, то он может установить заказу более высокий статус “Допущен к ФП”.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJqSURBVHgBXVM9UxNRFD3v7QchBNkQRRgtdhztcFxKO1JZWAQ67bQzVZJfkOQXGCpKx0orhcI6dJbJjCWOboEjUZcsDIwhm7znvRsWN9mZl7zdd8/9OOc8gZnnyy42hYmSUNjSgBt/FOjSbzcao7lRhp+OF8mm8waONURdSlQLiwL5nIBlTo4HQ00L+HWqEI3QimxK9BLhdYIYHKHtLAhvLS/xlwDhOYEiwJCgREB+QWDOFggOFeQn3T16jiInMTkBVy7cEN4qgX8EDFY+xtiJNA5MCYequJSwvnoi3FstGqwHb/4r6gStic4u3KyN7/fXDGpRIwjV2yiDatJi8hCsQqsVvzwWOHymMbRRNC0D9ZWlSdvBmfLXy3gxSywB67QavA+eIMyWheMMgN+h3pJ06s3bQHhBIQrNGaCjgI8JmP5rvRKafeInn5MQAiXmwGNyIhqYAvwU2KXVxkRKfwRsU51ux4Q3oFgmlmNkAhhrDdI+npsU89LgS6DIYD4zx3AM+b9LSQz70UgjY9HOxCaTRck7V+A9+roxn+qMFbEMEXuDzSWVxj7P75BxVj7EZLWuRmhSoW0CTKkhJOpsMjYWO9SkyL3+sa7cfA9kP8NJyDISyVJOtSO8Xl4UbobmOQrIlWTt2Inn99DKfkMFt4GTmkAvr31NijCpMS+C7oeBylJOuHcKEsd9kvxU7ay/QvXaynffoa2fCm/5gYznYyszN2PSkSs6JBvL/bPPkqtuZE2sPHWZzEs0bAsVNhaDMvbkmBOFF8CfMwXFFp9DY+oyTc1K1qb5G3QrH7FH4iANnxrZZ74elnGQjv8HJFoKx28SXRAAAAAASUVORK5CYII=""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОТКЛОНЕН РУКОВОДИТЕЛЕМ</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Руководитель ознакомился с ЗП, решил, что расход не заслуживает рассмотрения на ФП, отклонил до ФП.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAF3SURBVHgBnVNLTgJBFKzu+YiKkU9iQtywcGscbyAngCu4ZKU3AG8gK5ZeQU6gN2ASly5kQ2KI6ICSKD3T7XutGCRIGCuZycz0e1U1r6sFFnDXxolwURUaNQOU7UeBkO6hSnBxXEdvvl7MHrpXyHlTNKTEeXFHIJ8V8Nyv5fepoQsYjDRUjEvlE9Epoh8C26xwk9sWQSkvQSRLkWgiiTSe30yoPFSYxJayMqkG+8W/mxkOrZUKEizEPdZBt43ylo+Hg5KzsnnRyX0/QRyjIj0Hjb1duXbzzEmB5iQEahIGwaaP1MhnJRNUWTfY8EVqAs8FeJtTGF8OSdo9FRukBWeDEEpt0Ikm/yGATSgP8Xo4NnZr1oUmVZtKirY8rOM2TtB6fFmfYTAClEKLz4UdYryBZkTxZJJVTli5PzQYvupQUQ+wcJjcDzR9D2ccrAxlI/O9vTzkaAI8jTU0ueXmX4dpHhxtB2hSMo/oNbBFBj0y1uF58S/P138C9tiWVsdJDOwAAAAASUVORK5CYII=""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ДОПУЩЕН к ФП</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (заказ попадает на ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Сотрудник финансовой службы (или сотрудник с нужными правами), который отвечает за подготовку всех данных для ФП, проверяет все без исключения ЗП со статусом “Утвержден руководителем”. Если заказ оформлен “как надо”, то заказу ставится статус “Допущен к ФП”. С этого момента заказ попадает в ближайшее ФП.&nbsp;</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFnSURBVHgBfVNLSgNBEH2JIhgEA1lINjrowsVssnUhjCcQb+AN4hG8gXqC+DmBJ0h040pmFrpQkRncuJBBAwERP2PVdFdP26anoKC6p17361dvACc+gagADijTH6DgpDqmHLwDAXxBDW0GCsiX+vC24BoWeEhlj9ePXYyu1nGeLyDhdWeC3soL+pu3hkFCwC3KN7m9vHncQnEaYc/H8mYZA5uJgAPZrANTX999DuvFH8pTRyHSGrDR5hvYf+hiqOtDUBH7bhdtNPj1C9jlfe7Ve+msCDfWglngQAsbUGYE3pmD6smr3qA5jbL2QqzByQcpLmA3mjSKjIvFiWLCYs2om5n+CY9rXvdIdHRvgw9lIfg99ySMKxY8cREql/IASrrOeIxY0+IsqsZprC0sOK9XaTQ1YDabGSE8Vr4MkT0t4ShvVVbeuMP22jMZR8VfK8shNhNfco/9M/0Lnj81HYvBxDAMLK3rxC/c3u0K6u5A0QAAAABJRU5ErkJggg==""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОТКЛОНЕН на ФП</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">На ФП было принято решение отклонить заказ и не ожидается, что к нему снова нужно вернуться на следующем ФП.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAF5SURBVHgBpVOxUsJAEH13SRgBRahsKexNSSkzVjb6C/6BLRWxopW/0A5KC0c/IR/gDOmsVHQwZEju1t1EHGSUAX1F5mZv39vN7juFJez3cAiNE1I4VUDzMxzyOUwNLqIOosV8NT80A9TdKrocOHd3NNyKgnKLazsj2JSQvlmQxWX2zkIBxl8CObmCO7eqfW+XiVrhJzA5F8kmNsxitEVEy4VUdre1X2roX8l5Nc4u1bk7LiScPNbsoemVMNrac1aSlztJHjNQhrZ2HHS9ml6bPO9E5iSD1krBd0rrk+eQIWveFsvAV97mArIh4vlr/BOaVSLKCJtCvMEIpYNhFv9BgI0l7tTKYMDGAG2gQbZwpVjbeb5F1DhCgwy13PJ6I0lfCWZK/VEHVznDeAhMTOFsbFZ2IpVnL4WVTYJAYo58xjdIase4pgRlE9uWGEV+UDnFemXI2YTJTxYmob6Z4uzbY1qEWNvRCFjkQDySC/CmYDFUhMFDB/eL+R+RgqGPNVhwFQAAAABJRU5ErkJggg==""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ПОЛНОСТЬЮ, выплат еще нет</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">На ФП была одобрена вся запрошенная сумма. По заказу еще не зафиксированы выплаты.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJHSURBVHgBdVM9aFNRFP7ufTcpbZo0seDQCD4hqxjBIZumuuiQKIKjKA7ipItDljbq0Em0OLjooCDUzWSRgqUKInSLOgUKiYNisS1J2vyQ9969nnvT/LySnuFxufd83znnO99jOBSJJVwAR1YxXGWAfXBdonPJ8fComkN1NJ/1D3YeURHCIl08EGEOMcXARO9ZdhWko+A0JJTEc7dJRHnUBgQGPIV1EeLJwAwBOcO4ILAhcfdlyW0hrUm4ftCVxTRPBmPcB86cuon0icywXcoORqk7KqQx+s6yl2BbAisTswRmQ/C54+dx7/QC4qGT+LGzgT2nPnjjEwzevkwdm8cXbllYDET8lecI9PriJxQqb9Do1um85htFd6J10kILKpq0gv6Z50I29ro1vCu/QDgYxcOzTxEORKmL2iBHi+w2kCUaJFnAT1CufTctf8xsIh3PYGHjjg9suqANKdKfY0zo6peLCbz8+djooMc5KgSxVJWr7P7OdaTjWWp9BsXKW6z/LuLr9X9Glz/NX4Mc7Q2KkqBPwW2p+4HIkEC3+yT1ypDESQ8NHAUbAjKWdqc1O4+O8tQt8gH6W9TJ250t3EjcNVvoaTBco5IK3V0Jx8U1a3cN1dglxIgkJSa5T8jt9ha+/V1FtVH2VXfqCl5bLVdyWOlZ+RlZ2SErTzOysgU23smmsga7zaGVLf1QW0UncgXvVQeTXkumtFH0gMzqMZHI5H9qe0fC66hlr43bvp9pNIy1OfJEckZ7xBDQpiBRYAofNnP4PJr/H/vP9nUo5Mw+AAAAAElFTkSuQmCC""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ПОЛНОСТЬЮ, всё выплачено</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Все средства, одобренные на заказ, были выплачены (через платежные документы 1С).</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJeSURBVHgBdVNNaBNREP7eZpNCk5pVsUIjuIEgeJCmoNCDqLEnL4ngUWgPPYi9VBDBHmyiHgoFaYMHL3qwIHgRTS5erFEQSi+SKh4ilaxIKiLSzV8pyeY95700aVbbOSSPmfm+mflmluEfi8zhAjQkBMNlBpg77jy9880W7lozsHrzWedhpmDofiTJcUMf0KD3MzC9HeYNAd4UaFY4BMeiUyeiFOwugQL3I6f7tag3SECNYS8jsCJxajzvbCEmSTQZkJX1gBb1HdRc4Hh4HLFj8d12KdtnUHdUSGKkz2POwfToeN53mMBsF3x68Dyun5pFyH8cn/6sotosd2NaH0OrxkcPXcR7zeNB0nvAXXmIQE/G3iBTfIpKo0zvZdcoshOpkxRap6JRj88985DfRLVh41nhIQZ8Bm6NPMCA16Au7G6OFNmpIEE0iDKvm6Bgr6mWX8fXEQvFMbs66QKrLmhDgvTXsIfJ6peyETz6fE/pIMfZz3RisYQjzM7OpcVCCWo9iGxxCblSFh+u/Fa6bNS/d3PkbZDldfrJXDt5Z3p8eFoFJOjtjyzujz5WJCHSQwJ7wYqADktep7YyVQpOfTERGAwjcGIEV1eCOHP0HOY/3kQiPIEAiTe5POYCC96+SnnaTAixKcJhA5bVjhoGar+KOPviiBplY8tCYXPNRdCwuSRIf7tNZ688do/CRNCxXCnzf+WygFPn+dY2UtInt5BmCwu0EFOBWTKJl1+X1IxdoNNueftnC80qT3e+AxlT0tMYi/Q3sZOfjswzk65tWN6IitOmwJFhAq/WZ/Cut6u/uBvxSjYbAqMAAAAASUVORK5CYII=""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ПОЛНОСТЬЮ, частичные выплаты</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Зафиксирована неполная выплата денег из одобренных средств.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAIvSURBVHgBdVM9aBRBGH0zt3uB3J05FSzuBCcQsAqckCJgoauVzZ2VlQTBRguDjUUKc/kpUgnGFF6hoAHB0qTRQjktLNJd/AEDgazNiYV4vyHc7s34zVxu9zZeHiwMM/Pe97433zIcwcQKLoOjoBiuM0AcbldoXfG6WHTn4A7eZ/2FWEDaSqBIG/etFIc1ysCs3rHsKEhPwWtIKInHfpuEFlALBAx5FGUrwXP2GBE5wzAQ2Yj4LVnx9+FoEa4PdGUryXPxkzxCzo/PwDmbD+3S7Xia3FEhzdF7MbECEbPweuQ0kVlInjpzCXcn55FNnMOXP1toevXgjI8wdFty+tQVfOKxGIr2iWjlDJGeX32Pjb2XaHTqtP4QaUU70TnpoC0qmovFoz1nEgLNTg2vdtaQiqfx4MIjpOw0uagFd3TIfgMFkkGO2VGBndq2sfw2vwsnm8f81u0I2bigF1KUP8cQ6OrXNifw9OuSyUG3cxz4vYtFKF9FNp1swbzA5t46brybMoHqXAahZ4NQsWYzt2AnOUrfl0MHZHd5+hn1P0avIFBt/zRfRIAGS08nk0IoVi6j1Fony6GIdnDz/Cx+/N1G6dtSREBJhYPfXXgdjFtwXSjHwR0SwSQCEW2/SU9Y3Xf/q+419GhjVf8XjKazF4AQGOZkELqyV1fw20dG2aDvJDlDyT80PQZEv/cjHfwi20252ifrs9BBH4dOnlRfYO3zYk+A5CGxwRTe7M7h4+D1f1Bu9z7HU1pNAAAAAElFTkSuQmCC""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ПОЛНОСТЬЮ, закрыт</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">На заказ была выделена вся запрошенная сумма. Выплата была частичная. Заказ закрыли принудительно через документ “Закрытие заказа”.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAGvSURBVHgBpZO/LkRBFMa/M3NZOsID3EKyOlsqVycU6xVUQrM8AZ5gr0j8qbRKCrUtlVvayn0AEipZzD2+Mxe7hOwmvmQ3M3PPnznn/EbwQ3OHqPsxNKBY4za1MxV0uO84YP92E/mgvXwu0jNMVXrY5cG2eP5r/6uqwjlBERQakPUmsZ+v4/ErgDmP93DtvNRobUZtBrgUyxwDoEbLJvepJILwpp2XCpYsSGIGltklUtMyw053C9mPytr8ZdVTbCNoyzNR5Vl3ebYj88es0+HOrqzFr87fZEFEpIWCDq9YYl9YN2vmNfNhzqbuBjIttG0+IcGaKwQ1ZramHWBUFbi0HjN7w0nZIEgoGzaKApsrGpepwz9lAXJbqOdNRpTnreMFSrg4b9sI6RtVxoQrCSVfuDDC2NV69YhzHqLqCZoMkBozhra/v0I+u4pp57HID8szK3h6uMLNX86kMfOJYY2D7ibOS5RbRHkS195ofNPIhI01fEzG+ziphnjUCRFC6KPcf0wMUpnAHmtrRrCK/mv66BEi6gzco923xzSoiLZir3BYiIyUylE2+4LPuT1o/w4rIa+laX/2rAAAAABJRU5ErkJggg==""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ЧАСТИЧНО, выплат еще нет</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (попадает на следующее ФП)</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAIySURBVHgBdVM9bxNBEH2z6+C4cGQEBR2HhGQ6zq4ozx2Cwv4JUKHQ2P4Ftn+BbSHxURk6OpIiEl1cUuEr44qjB8mxC3DI3TCzd4cvSBnpPnZ25s3M27eE/+z+KwR2D20wOrL01MeEUNahAUZnh4iK8ZT/eDPUylsMxNEjK2/e7XLCIEPuyzEm2wpG0XOs/gFo8o0tTo0lHxqUYC4Ax6SVFYDhS2RX1h6VCPElhxdltBSkpAFa2ZTI50uX3F++xET9NR81/a5CAQQm9XfoSczYSqHyLx6Ir08P3sicBt+05WKyWtVHm4wJ1l+Tfu5TEAKNtS38QUt4kbl1PkZUTD5omgERDWUjqDbNLPcvX2DCzHPlKS6hYxKCL5WVtOkVdpmfJcx9w9wiToJ8HGcJjpVjqd4ukRJkJeEiJSw3qfLBEM1iAdkscK+4Fwu5e+wOyjO4xtYhhgIykjEG1SZ9ui5OASJX0UonmWm7OvcmxPv1ghvSZWe/gbv5vpWulcNMXHLebmhRX2ZybCuZwVOQg5TA6PcC33cEiSZMqlDhH0dJ7JQW1F+jl8dsFkJekpxDHiGykfvrb9EVAE9VqdK2P04Q3X6Km8bikew/vvUE5z9P8EWDK3dwJgU+u46yZFlPrKgxiTFdHuJjKuWxSLmCU5urUTShxxrH6clY66QsokKgmonjnZR3l0lAyvsYSlA3vzggykZOXxw78OlW4q5cpqI5aTOGicFDp5HUoozsI7nO82L8X7vf+iUpJ/ZpAAAAAElFTkSuQmCC""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ЧАСТИЧНО, выплачено всё</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Например, сумма заказа 100 рублей, было одобрено 45 рублей (частично), все 45 рублей были выплачены. Но остается еще выделить на заказ 55 рублей, поэтому заказ считается всё еще не полностью одобренным и он будет попадать на следующее ФП до тех пор, пока вы либо не выделите на него всю сумму (до 100 руб.), либо не закроете заказ через документ “Закрытие заказа”.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJJSURBVHgBdVPPjtJwEP7mV1bWxF1705slMWH1IvAE5QngCfx3MW5MFl7AwhMUYiJrYoI8gfIES+LRRJp4cePBevBMhYOy0o4zLZVqspP8KJ3fzDcz33wl/Ge3X8C19tACoy2vjvqYEMh7YID+56cIi/GU/3HGsMtreOLokCW/vLvlhEGG0ifHGKyvoh8+QvQXQJOvrHFmLKpBgxLMBGBKWlkBGDWJPJF3h0qEeMPBRRlNBSlpgFY2JarxJk3unh9joH67BlufUSCAwKD6Ch2J8S0pVP7Jnvi6dDSSOQ2+asvFZLWDGlpkjLv8mHRzn4IQyNe28BtN4UXm1vkYYTH5sGE8IurJhXvQMOPcf/4EA2aeKU9xCW2TEGpSWUkb/sMu88OEuWuYm8SJm4+TWoKpcizVWyVSgixJuMgIy02qTAzROBaQ1RyV4l0s5O5xuijH4BJbBugJSF/G8A4a9PayOAUI04qWdLI1bVfnXgV4s5xzXbps79dxK7+3pGvlcCsuTJ81nuPD44UvFRdyfFlbJDM4CnKYERj+muPbjiDRhMkUat7f/379+FMF125WwJWKjcmkIyC91VzIS5IfkCNE1vPc6ilOBMBRVaq0laxF4ji6iOzYNqtvO4pTZF+Tj07Bd18TV0fZylMlIop2rNg2luvIrr5EJ46zzdywUim3RMquamajUt5HLydxSL4vC3HSZPI8TL9MQBb8UpnO9IjMfTmu7i3Z8DD/DjI6sp1rOw+2PQzvjMhJDO6lGsksVLIl+J18zrPiGv8A/5EPmAxwnO0AAAAASUVORK5CYII=""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ЧАСТИЧНО, частичные выплаты</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Например, сумма заказа 100 рублей, было одобрено 45 рублей (частично), выплачено всего 30 рублей. Поэтому появляется красная точка на иконке.&nbsp;</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Для полного одобрения заказа необходимо одобрить еще 55 рублей, поэтому заказ считается всё еще не полностью одобренным и он будет попадать на следующее ФП до тех пор, пока вы либо не выделите на него всю сумму (до 100 руб.), либо не закроете заказ через документ “Закрытие заказа”.</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAIrSURBVHgBdVNNbtNgEH3zOSVlkSpI7DESUipWTuAA9gmSG1BWCIjU5AROTtBULbRISGlPADlBsgcRL+kqZo9QSBaQUnuYsfs1bquO5L/5Zt7MvHkm3LAnB/CdDTTBaMmnqz4mRPIdGaD//TXiYjzZF3eIanmFUBwdcuTO61NOGWQoe3KCweo++vFLzK8ANPneCmPjkAcNSjERgBFpZQVgeBK5K98ulQjJBUfnZQQKUtIArWxK5PFFltw9e4OB+qseqvqcRwIIDGof0JGYPUcKlf9wKL4ubR/JnAYzbbmYrFbx0CRj/MW3tGt9CkKgPW0L/xAILzK3zseIi8lbDRMSUU8O/ErDDK3/7BUGzDxRnpISWiYleFJZSdu/xi7zTsrcNcwBcerbcTJLMVKOpXqzREqQIwnnOWHWpMqpIRomArKc4nHxLBFyNzhblGtwhy0i9ASkL2OElQZ9uivOtJ+HeUVHOrk0bVfnXkY4WUy5Ll22Nut4ZM8d6Vo5zMTVfriD9rNQFdG0AbK2uczgKshWTmD8d4ofa4JEEyZXqOEgwNsHLyCd+LX36NiY5VTIS9PfkEuIrFt/7Ri7AuCqKlXaQqis33WZZzM++BJyEURGcYvsa/L2MfjpR+LaUb5ySnPVC58uaDzG4c8THH7tx7rWJMk34ziZlEVU8FUzSbKW8hqgAPLu16mA9ASeLkfOb5ywCm5/tYne1c90DeB2J9YbyzUSjM/yO0+K4f8BIuYDazQGKowAAAAASUVORK5CYII=""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОДОБРЕН ЧАСТИЧНО, закрыт</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (не попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Заказ был одобрено частично, по нему были какие-то выплаты, но заказ был принудительно закрыт через документ “Закрытие заказа”. С этого момента заказ перестанет появляться на ФП.&nbsp;</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAIPSURBVHgBjVPPaxNBFP7ezCba1KTJRUoRukJQD0L2KJSC0la9SIP/gIf+AebaU9dTQQ+ag94q4s2DtPXs0h68GxVBQWyKUkQPpqaNMbs747xNN82PFXyw7PDmfd/M++Z7hKEoruIyBBY1oUyAfZSumXXND3Gnvox6fz3FC9tF3hrHiklUrKyAlSGQ1d1WHQ3la/i/FLTCg+DQELlo8J7sgTPYWjhXLh9kfyBIdUCCjk+RBJEmFPIFzExeu7Sz/+F6bgbPGttoCy7gk69eKDuPFtexNu8hm8oPdxblHi94eHhjHTcv3nIYw3lhr8Imgcrn8B32DndxvlDC2tzLARJec473uObtn1fce4X1ElJiJZUT2Pu9iyVvboRkanx6ABzVmFrWKRK6eA+vx05Lh1LdnrsAL/p//PkG2XSXpAc2fw4daLS/hXUq3oXOnLEG+u0n4RgGx9H6GkDgP6LZaZhvP3FPaKDO10k6nVv4l7DsDRM1vsFm0NKJ4CVvPlHYiMAYi90pKMRGcKAwNTYKbvqNgf5jklPWRORKtrb4tIxtpVA90coZxSfwYudpDxzHMEnp5Ky5Aao8F9Hb2feNlX1sTU+edb7LLyBKFpNvWUrP4vn7J7WghSs8D8fDZEikD1dI3GZjsffFkTdYZNYpaCqoENWwDTceppGz2NpSwDX2LkHDiQjMS0FhkzQ2uOX++r+xFQVtNAAxCAAAAABJRU5ErkJggg==""></span></span></p></td>
                     |<td style=""border-bottom:solid #666666 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ЗАКРЫТ БЕЗ ВЫПЛАТ </span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">(не попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">Заказ был одобрен полностью или частично, но был закрыт принудительно без осуществления выплат по нему.&nbsp;</span></p></td></tr>
                     |<tr style=""height:0pt"">
                     |<td style=""border-bottom:solid #434343 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:0pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""><span style=""border:none;display:inline-block;overflow:hidden;width:16px;height:16px;""><img width=""16"" height=""16"" alt="""" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHZSURBVHgBfVM7TxtBEP5274ETiGKDRGLR2FLSJcrlH4RfAF1KlJIqiIoGYURDCRWiAVHSQUkD/ANOgg4k3CAQ4nEGjMB7t8vMHg+f5WOkPd0+vsfOzAp0xP4S/ggXI0Jj1AAVuygQ0jdUCWZ/j6Pefl68/Oytoui1MCMlJgY+CZT6BDw33X5oGRrAeUNDxVhQPhH9Q/RKYMEKO8VeEZRLEkTSNRJNJJHG1Z0JlYdhJrFHWZlUg6GBfDCHQ3vlfgkWYox1sLeEykcfx9/KTi64+WDQWxAZJ4cnCeIYw9JzMDP4OV/5PDKYXNY4PjMZJ/2UJyEwKmEQfPCRG4NFgam/EvPrWZJSn2SCEZf+gx4/tXdQN3Z0i+oXgek1jbkxiepXrhDAZX4nZR1XabwQi8w6V7quYlPhmv+opKMztkNjczE35pB6usa9QRFKbbAZNU2uMt97ZUtnwCmBNRMKbl3Xxc73Icdmt6v9iJP5NtekenSqcd9CVf4cx26cYPHsWue6aAdbwgagFBb5XVjNuAe1iNqTSZJ8Hqt8cmlweatDRRig4zG5j6j5Hv5zYxWoNwrP5aUkI2oCFzcamtwyOPOY2oNb2wFq1Jm/aBrYQwZ1MrZJhd/gK7effwIj9b36F2oqtAAAAABJRU5ErkJggg==""></span></span></p></td>
                     |<td style=""border-bottom:solid #434343 0.5pt;border-top:solid #666666 0.5pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"">
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:2pt;margin-bottom:0pt;""><span style=""font-size: 10pt; font-family: Arial; color: rgb(0, 0, 255); background-color: transparent; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">ОТЛОЖЕН ДО СЛЕДУЮЩЕГО ФП</span><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;""> (попадает на следующее ФП)</span></p>
                     |<p dir=""ltr"" style=""line-height:1.2;margin-top:6pt;margin-bottom:6pt;""><span style=""font-size: 10pt; font-family: Arial; background-color: transparent; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;"">На ФП было принято решение, что запрошенный заказ признан как необходимый, но на текущем ФП нет средств для того, чтобы начать выделение средств на этот заказ. Заказ еще не признан отклоненным, его откладывают “до лучших времен”. Он будет появляться на каждом следующем ФП, пока ему не установят статус “Отклонен на ФП” или не аннулируют через документ “Закрытие заказа”.</span></p></td></tr></tbody></table></div><br></span></div>
                     |
                     |
                     |</body></html>";

КонецПроцедуры
